name: mo
services:
  postgis:
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=osm
    user: postgres
    networks:
        - net
    ports:
      - "5432:5432"
    volumes:
      - osm-data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=nicolaj.niels1+pgadmin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5433:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - net
volumes:
  osm-data:
  pgadmin-data:
networks:
  net:
